spring:
  application:
    name: management
  datasource:
    url: ${DATABASE}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
emailConfirm:
  credentials:
    email: ${CONFIRMATION_MAIL}
    password: ${APPLICATION_PASSWORD}
api:
  base: api/v1
  domain: ${DOMAIN}
  redirectUrlEmailVerify: ${URL_EMAIL_REDIRECTION}
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET:gameyard-s3-assets}
jwt:
  secret:
    key: ${JWT_SECRET}
  time:
    expiration: ${JWT_EXPIRATION}
  email:
    expiration: ${JWT_EMAIL_EXPIRATION}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.access: DEBUG
    com.amazonaws.util.VersionInfoUtils: ERROR
