import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import { AuthContextProvider } from "@/context/AuthContext";
import { LoaderContextProvider } from "@/context/loaderContext";
import { MainComponent } from "@/components/shared/MainComponent";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LoaderContextProvider>
      <AuthContextProvider>
        <AppContextProvider>
          <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased min-h-screen`}>
              <MainComponent>
                {children}
              </MainComponent>
            </body>
          </html>
        </AppContextProvider>
      </AuthContextProvider>
    </LoaderContextProvider>
  );
}
