import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { AuthContextProvider } from "@/context/AuthContext";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <AppContextProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased min-h-screen`}
          >
            <Header />
            <div className="containerLayout flex-grow bg-[--background-color] flex flex-col justify-center ">
              {children}
            </div>
            <Footer />
          </body>
        </html>
      </AppContextProvider>
    </AuthContextProvider>
  );
}
