import type { Metadata } from "next";
import { AppContextProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppContextProvider>
      <main>
        <section>{children}</section>
      </main>
    </AppContextProvider>
  );
}
